[2024-03-26T09:57:19.927] [ERROR] error - CustomError: [1] Unauthorized
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:16:19
    at Generator.next (<anonymous>)
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:4:12)
    at auth (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:11:26)
    at Layer.handle [as handle_request] (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:328:13)
    at D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:346:12) {
  code: 401,
  status: 'error'
}
[2024-03-26T13:58:01.213] [ERROR] error - CustomError: [1] Unauthorized
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:16:19
    at Generator.next (<anonymous>)
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:4:12)
    at auth (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:11:26)
    at Layer.handle [as handle_request] (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:328:13)
    at D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:346:12) {
  code: 401,
  status: 'error'
}
[2024-03-26T13:58:02.743] [ERROR] error - CustomError: [1] Unauthorized
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:16:19
    at Generator.next (<anonymous>)
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:4:12)
    at auth (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:11:26)
    at Layer.handle [as handle_request] (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:328:13)
    at D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:346:12) {
  code: 401,
  status: 'error'
}
[2024-03-26T13:58:03.468] [ERROR] error - CustomError: [1] Unauthorized
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:16:19
    at Generator.next (<anonymous>)
    at D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:4:12)
    at auth (D:\Dev SIPPP\PMO\usman\src\middleware\auth.ts:11:26)
    at Layer.handle [as handle_request] (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:328:13)
    at D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Dev SIPPP\PMO\usman\node_modules\express\lib\router\index.js:346:12) {
  code: 401,
  status: 'error'
}
[2024-03-26T14:27:19.803] [ERROR] error - CustomError: Data Tidak Ada
    at D:\Dev SIPPP\PMO\usman\src\services\api\v1\refAplikasi-api.ts:165:15
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\usman\src\services\api\v1\refAplikasi-api.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 500,
  status: 'error'
}
[2024-03-26T14:39:54.156] [ERROR] error - CustomError: ENOENT: no such file or directory, unlink 'D:\Dev SIPPP\PMO\usman\src\public\image\aplikasi-1711438270745.png'
    at D:\Dev SIPPP\PMO\usman\src\services\api\v1\refAplikasi-api.ts:169:19
    at Generator.throw (<anonymous>)
    at rejected (D:\Dev SIPPP\PMO\usman\src\services\api\v1\refAplikasi-api.ts:29:65) {
  code: 500,
  status: 'error'
}
[2024-03-26T14:51:08.140] [ERROR] error - CustomError: Data Tidak Ada
    at D:\Dev SIPPP\PMO\usman\src\services\api\v1\refGroup-api.ts:109:19
    at Generator.next (<anonymous>)
    at fulfilled (D:\Dev SIPPP\PMO\usman\src\services\api\v1\refGroup-api.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 422,
  status: 'error'
}
